SELECT 
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_NAME, A.CATEGORY, B.AUTHOR_ID
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC