-- 코드를 작성해주세요
SELECT 
    d.ID,
    d.EMAIL,
    d.FIRST_NAME,
    d.LAST_NAME
FROM DEVELOPERS d
JOIN SKILLCODES s
    ON s.CATEGORY = 'Front End'
WHERE d.SKILL_CODE & s.CODE > 0
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID;