SELECT 
    B.USER_ID,
    B.NICKNAME,
    SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID, A.STATUS
HAVING STATUS = 'DONE' AND SUM(A.PRICE) >= 700000
ORDER BY SUM(A.PRICE) ASC