SELECT 
    C.EMP_NO,
    A.EMP_NAME,
    CASE 
        WHEN AVG(C.SCORE) >= 96 THEN 'S'
        WHEN AVG(C.SCORE) >= 90 THEN 'A'
        WHEN AVG(C.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    
    CASE 
        WHEN AVG(C.SCORE) >= 96 THEN A.SAL * 0.2
        WHEN AVG(C.SCORE) >= 90 THEN A.SAL * 0.15
        WHEN AVG(C.SCORE) >= 80 THEN A.SAL * 0.1
        ELSE A.SAL * 0
    END AS BONUS
FROM HR_EMPLOYEES AS A
JOIN HR_DEPARTMENT AS B 
ON A.DEPT_ID = B.DEPT_ID
JOIN HR_GRADE AS C 
ON A.EMP_NO = C.EMP_NO
GROUP BY C.EMP_NO
ORDER BY C.EMP_NO ASC