-- 코드를 작성해주세요
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE AS A
JOIN ITEM_INFO AS B ON A.PARENT_ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO AS C ON A.ITEM_ID = C.ITEM_ID
WHERE B.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC