SELECT 
    COUNT(*) AS FISH_COUNT,
    CASE 
        WHEN CAST(SUBSTR(TIME, 6,2) AS UNSIGNED) >= 10 
        THEN CAST(SUBSTR(TIME, 6,2) AS UNSIGNED)
        ELSE CAST(SUBSTR(TIME, 7,1) AS UNSIGNED)
    END AS MONTH
FROM FISH_INFO
GROUP BY MONTH
ORDER BY LENGTH(MONTH) ASC, MONTH ASC;